Metrics/MethodLength:
  Max: 15
Style/GlobalVars:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Naming/MethodParameterName:
  AllowedNames:
    - x
    - y
    - t
    - id
Metrics/ClassLength:
  Enabled: false

